add init.d script

diff --git a/init b/init
--- a/init
+++ b/init
@@ -1,153 +1,104 @@
-#! /bin/sh
-### BEGIN INIT INFO
-# Provides:          logbot
-# Required-Start:    $remote_fs $syslog
-# Required-Stop:     $remote_fs $syslog
-# Default-Start:     2 3 4 5
-# Default-Stop:      0 1 6
-# Short-Description: IRC log bot
-# Description:       IRC log bot
-### END INIT INFO
+s some perhaps unnecessary complexity going on in the relationship between
+#  Forever and the server process. See: https://github.com/indexzero/forever
+#
+# 1) Forever starts its own watchdog process, and keeps its own configuration data 
+# in /var/run/forever.
+#
+# 2) If the process dies, Forever will restart it: if it fails but continues to run, it 
+# won't be restarted.
+#
+# 3) If the process is stopped via this script, the pidfile is left in place; this helps 
+# when issues happen with failed stop attempts.
+#
+# 4) Which means the check for running/not running is complex, and involves parsing 
+# of the Forever list output.
+#
+# chkconfig: 345 80 20
+# description: irc logger
+# processname: logbot
+# pidfile: /var/run/logbot.pid
+# logfile: /var/log/logbot.log
+#
 
-# Author: Wil Asche <wil@asche.us>
+# Source function library.
+. /etc/init.d/functions
 
-# Do NOT "set -e"
-
-# PATH should only include /usr/* if it runs after the mountnfs.sh script
-PATH=/sbin:/usr/sbin:/bin:/usr/bin:/usr/local/bin
-DESC="IRC log bot"
-EXE=node
 NAME=logbot
-DAEMON=/usr/local/bin/$EXE
-DAEMON_ARGS="$NAME.js"
-PIDFILE=/var/run/$NAME.pid
-SCRIPTNAME=/etc/init.d/$NAME
+SOURCE_DIR=/usr/local/logbot
+SOURCE_FILE=logbot.js
+user=unreal
 
-# Exit if the package is not installed
-[ -x "$DAEMON" ] || exit 0
+pidfile=/var/run/$NAME.pid
+logfile=/var/log/$NAME.log
+forever_dir=/var/run/forever
 
-# Read configuration variable file if it is present
-[ -r /etc/default/$NAME ] && . /etc/default/$NAME
+node=node
+forever=forever
+sed=sed
 
-# Load the VERBOSE setting and other rcS variables
-. /lib/init/vars.sh
+export PATH=$PATH
 
-# Define LSB log_* functions.
-# Depend on lsb-base (>= 3.2-14) to ensure that this file is present
-# and status_of_proc is working.
-. /lib/lsb/init-functions
+start() {
+  echo "Starting $NAME node instance: "
 
-#
-# Function that starts the daemon/service
-#
-do_start()
-{
-	# Return
-	#   0 if daemon has been started
-	#   1 if daemon was already running
-	#   2 if daemon could not be started
-	start-stop-daemon --start --quiet --pidfile $PIDFILE --exec $DAEMON --test > /dev/null \
-		|| return 1
-	start-stop-daemon --start --quiet --pidfile $PIDFILE --exec $DAEMON -- \
-		$DAEMON_ARGS \
-		|| return 2
+  if [ "$foreverid" == "" ]; then
+    # Create the log and pid files, making sure that the target use has access to them
+    touch $logfile
+    chown $user $logfile
+
+    touch $pidfile
+    chown $user $pidfile
+
+    # Launch the application
+    daemon --user=root \
+      $forever start -p $forever_dir --pidfile $pidfile -l $logfile \
+      -a -d $SOURCE_DIR $SOURCE_FILE
+    RETVAL=$?
+  else
+    echo "Instance already running"
+    RETVAL=0
+  fi
 }
 
-#
-# Function that stops the daemon/service
-#
-do_stop()
-{
-	# Return
-	#   0 if daemon has been stopped
-	#   1 if daemon was already stopped
-	#   2 if daemon could not be stopped
-	#   other if a failure occurred
-	start-stop-daemon --stop --quiet --retry=TERM/30/KILL/5 --pidfile $PIDFILE --name $NAME
-	RETVAL="$?"
-	[ "$RETVAL" = 2 ] && return 2
-	# Wait for children to finish too if this is a daemon that forks
-	# and if the daemon is only ever run from this initscript.
-	# If the above conditions are not satisfied then add some other code
-	# that waits for the process to drop all resources that could be
-	# needed by services started subsequently.  A last resort is to
-	# sleep for some time.
-	start-stop-daemon --stop --quiet --oknodo --retry=0/30/KILL/5 --exec $DAEMON
-	[ "$?" = 2 ] && return 2
-	# Many daemons don't delete their pidfiles when they exit.
-	rm -f $PIDFILE
-	return "$RETVAL"
+stop() {
+  echo -n "Shutting down $NAME node instance : "
+  if [ "$foreverid" != "" ]; then
+    $node $SOURCE_DIR/prepareForStop.js
+    $forever stop -p $forever_dir $id
+  else
+    echo "Instance is not running";
+  fi
+  RETVAL=$?
 }
 
-#
-# Function that sends a SIGHUP to the daemon/service
-#
-do_reload() {
-	#
-	# If the daemon can reload its configuration without
-	# restarting (for example, when it is sent a SIGHUP),
-	# then implement that here.
-	#
-	start-stop-daemon --stop --signal 1 --quiet --pidfile $PIDFILE --name $NAME
-	return 0
-}
+if [ -f $pidfile ]; then
+  read pid < $pidfile
+else
+  pid = ""
+fi 
+
+if [ "$pid" != "" ]; then
+  # Gnarly sed usage to obtain the foreverid.
+  sed1="/$pid\]/p"
+  sed2="s/.*\[\([0-9]\+\)\].*\s$pid\].*/\1/g"
+  foreverid=`$forever list -p $forever_dir | $sed -n $sed1 | $sed $sed2`
+else
+  foreverid=""
+fi
 
 case "$1" in
   start)
-	[ "$VERBOSE" != no ] && log_daemon_msg "Starting $DESC" "$NAME"
-	do_start
-	case "$?" in
-		0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
-		2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
-	esac
-	;;
+    start
+    ;;
   stop)
-	[ "$VERBOSE" != no ] && log_daemon_msg "Stopping $DESC" "$NAME"
-	do_stop
-	case "$?" in
-		0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
-		2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
-	esac
-	;;
+    stop
+    ;;
   status)
-       status_of_proc "$DAEMON" "$NAME" && exit 0 || exit $?
-       ;;
-  #reload|force-reload)
-	#
-	# If do_reload() is not implemented then leave this commented out
-	# and leave 'force-reload' as an alias for 'restart'.
-	#
-	#log_daemon_msg "Reloading $DESC" "$NAME"
-	#do_reload
-	#log_end_msg $?
-	#;;
-  restart|force-reload)
-	#
-	# If the "reload" option is implemented then remove the
-	# 'force-reload' alias
-	#
-	log_daemon_msg "Restarting $DESC" "$NAME"
-	do_stop
-	case "$?" in
-	  0|1)
-		do_start
-		case "$?" in
-			0) log_end_msg 0 ;;
-			1) log_end_msg 1 ;; # Old process is still running
-			*) log_end_msg 1 ;; # Failed to start
-		esac
-		;;
-	  *)
-	  	# Failed to stop
-		log_end_msg 1
-		;;
-	esac
-	;;
+    status -p ${pidfile}
+    ;;
   *)
-	#echo "Usage: $SCRIPTNAME {start|stop|restart|reload|force-reload}" >&2
-	echo "Usage: $SCRIPTNAME {start|stop|status|restart|force-reload}" >&2
-	exit 3
-	;;
+    echo "Usage:  {start|stop|status}"
+    exit 1
+    ;;
 esac
-
-:
+exit $RETVAL
